.PHONY: clean All

All:
	@echo "----------Building project:[ PrimeFinder - Debug ]----------"
	@"$(MAKE)" -f  "PrimeFinder.mk"
clean:
	@echo "----------Cleaning project:[ PrimeFinder - Debug ]----------"
	@"$(MAKE)" -f  "PrimeFinder.mk" clean
